### PR TITLE
Use getWidth() and getHeight() in ofVideoGrabber and ofImage

### PR DESCRIPTION
**Pull request by nanu-c**
This includes also a minor update to complie lpmtX2 on ubuntu

### CODE REVIEW

**Comment by jamet** [comment]
hey,
that's what i used to comment :)

i will the merge without testing, anyway if a problem occurs, it will be easily reverted.

i am using ubuntu 14.04.1, and had the same gtk error, this due to a bug ( probably from lib gtk3-dev), if you uninstal it and recompile without, it should work ok. (maybe you will have to recompile OF as well to get rid of gtk3).

for the gui point, true it's not that easy... giladx worked on a remote gui app( remoteX), but i 'm getting problem to run it (big cpu load), maybe you should give it a try. the problem is that it lacks few features...
you could also try Twisty from giladx repo or my fork (include sampler tweek for my use of the sampler fucntionnality), which is a puredata controller.

we could discuss further, but it my opinion it's kind of a good thing to have a "client-remote" type of gui to let the main lpmt thread do only the display job and have best perf, the problem with that is to create a gui that can get all the initialised parameter of the display thread (nb of surface, cams, etc...).

other thing is that there is quite a lot of osc messages implemented, which means it can also be easy to make your own gui depending on your own needs whith app like touchosc (there is a more or less working example in the repo).

i have not yet used lpmt in live, still testing and developping for my own needs, but i plan to use in a live video projected mapping of juggling ball manipulation filmed and sampled by two or more webcams.

to make that i use v4l2loopbacks, and i must say that i don't have that much problems but iam using the github master, with the official package from the ubuntu repo it does'nt work (i opened a bug case..).

anyway, let's keep in touch, you could message me and gilad_x on openframeworks, and i would like to know as well how you plan to use this tool :+1:

**Comment by Giladx** [comment]
Hey jamet & Aaron whats up I just updated remoteX with more functions (I think its all there)

**Comment by nanu-c** [comment]
Hey Giladx,
that's a nice one. In my opinion we should replace the gui- functionality  in lpmt with this one to have it separated.
For that we have to implement also the other way round that remoteX can get OSC messages from lpmt for the configurations. For example how many active quads exists...

In remoteX the quad selection slider is not working that well, because it's a float slider and i can't select quad 3,56 or quad 3,41. Quad 3 is only selected when i hit the 3.00.

Also it would be nice to have the different modes more present and not only with shortcuts.
yeay

**Comment by nanu-c** [comment]
*mask + edgeblend are not working together.

**Comment by Giladx** [comment]
Thanks Aaron yes I agree with everything you said. Also see our discussion here https://github.com/VideoMapping/remoteX/issues/1#issuecomment-134898935

**Comment by jamet** [comment]
i updated remotex with sampler gui module, and tried to work a bit on cpu load.

@moxor , the mask and edgeblend are effectively not working together, and it has never worked, don't really know why.

as for the slider, might be a good idea to take a radio box instead

**Comment by nanu-c** [comment]
or we gona use a matrix for multiple selections and to turn of camera on 3 quads at the same time!

**Comment by jamet** [comment]
i was thinking of that too :).
might be a good idea to take a matrix, but the one question is how we pass every variables from lpmt config (nb of quads, cams, etc) to the gui at setup?
was thinking of xml, but .... ideas? :)

**Comment by nanu-c** [comment]
maybe we can do it like implementing a osc mesage wich states "getConfig" and lpmt responds with a osc message including all the config?

**Comment by jamet** [comment]
i guess it would be a solution, but i don't know how much data you can put in one osc message?

**Comment by nanu-c** [comment]
There are two possibilities. We can bundle osc messages with ofxOscBundle or send xml also with osc. In /examples/addons/oscSenderExample/ is an example for sending a jpg file. The way is to load it in the buffer and then send.

**Comment by nanu-c** [comment]
Other question. Maybe it is better for the performance of the gui to use a cross-pattform gui-framework like wxwidget and not openframeworks?

**Pull request merged**
